spring.application.name=backend_ws

server.tomcat.threads.max = 1

server.port=${PORT:8080}

spring.data.rest.detection-strategy=annotated
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.template.mandatory=true
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.web.socket.messaging=DEBUG
logging.level.org.springframework.messaging=DEBUG
logging.level.org.springframework.messaging.simp=DEBUG
logging.level.org.springframework.messaging.simp.stomp=DEBUG
logging.level.org.springframework.web.socket.sockjs=TRACE
logging.level.org.springframework.web.servlet=DEBUG